#!/usr/bin/env python3
"""Compile the shared GLSL sources (src/video/shader_src.h) to SPIR-V for the Vulkan backend.

Usage: python tools/compile_shaders.py [path/to/glslang.exe]
Writes src/video/spv_shaders.h (committed, so building does not need glslang).
"""
import os
import re
import struct
import subprocess
import sys
import tempfile

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
glslang = sys.argv[1] if len(sys.argv) > 1 else r"F:\_ref\glslang_dl\bin\glslang.exe"

src = open(os.path.join(root, "src", "video", "shader_src.h"), encoding="utf-8").read()


def grab(name):
    m = re.search(r"static const char \*const %s = R\"GLSL\((.*?)\)GLSL\";" % name, src, re.S)
    if not m:
        raise SystemExit("shader %s not found" % name)
    return m.group(1)


common = grab("kCommon")
jobs = [
    ("quad_vert", "vert", grab("kQuadVert")),
    ("quad_frag", "frag", grab("kQuadFrag")),
    ("rect_vert", "vert", grab("kRectVert")),
    ("present_frag", "frag", grab("kPresentFrag")),
    ("overlay_frag", "frag", grab("kOverlayFrag")),
    ("shadow_mask_frag", "frag", grab("kShadowMaskFrag")),
    ("shadow_blur_frag", "frag", grab("kShadowBlurFrag")),
    ("shadow_comp_frag", "frag", grab("kShadowCompFrag")),
]

out = ["// Generated by tools/compile_shaders.py -- do not edit.", "#pragma once", "#include <cstdint>", ""]
with tempfile.TemporaryDirectory() as td:
    for name, stage, body in jobs:
        f = os.path.join(td, "%s.%s" % (name, stage))
        open(f, "w", encoding="utf-8").write(common + body)
        spv = os.path.join(td, name + ".spv")
        r = subprocess.run([glslang, "-V", "-S", stage, f, "-o", spv], capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stdout, r.stderr)
            raise SystemExit("compile failed: " + name)
        data = open(spv, "rb").read()
        words = struct.unpack("<%dI" % (len(data) // 4), data)
        out.append("static const uint32_t spv_%s[] = {" % name)
        for i in range(0, len(words), 8):
            out.append("\t" + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",")
        out.append("};")
        out.append("")
        print(name, len(words) * 4, "bytes")

open(os.path.join(root, "src", "video", "spv_shaders.h"), "w", newline="\n").write("\n".join(out))
